# Generated by Django 5.2.1 on 2025-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects_images/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies (e.g., Django, Python, Bootstrap)', max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
