# Generated by Django 5.2.1 on 2025-05-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_featured_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
