# myportfolio_site/render.yaml

services:
  - type: web
    name: myportfolio
    env: python
    # This buildCommand will now install dependencies, run migrations, and create the superuser.
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations # Ensure migrations are fresh
      python manage.py migrate        # Apply database migrations
      # Create superuser non-interactively using environment variables.
      # '|| true' ensures the build doesn't fail if the user already exists on subsequent deploys.
      python manage.py createsuperuser --noinput || true
      python manage.py collectstatic --noinput
    startCommand: "gunicorn myportfolio.wsgi:application" # As per Procfile
    plan: starter # Or 'free' if Render has a free tier for web services (check current offerings)
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render will generate a strong secret key for you
      - key: WEB_CONCURRENCY
        value: 4 # Number of Gunicorn workers (adjust based on your plan/CPU)
      - key: DATABASE_URL
        fromDatabase:
          name: myportfolio_db # Name of your database service below
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "myportfolio.onrender.com,yourcustomdomain.com" # Replace with your Render URL and any custom domains
      - key: DJANGO_DEBUG
        value: "False" # IMPORTANT: Always False in production!

      # --- ADD THESE ENVIRONMENT VARIABLES FOR SUPERUSER CREATION ---
      - key: DJANGO_SUPERUSER_USERNAME
        value: Skillz # <-- REPLACE with your desired admin username
      - key: DJANGO_SUPERUSER_EMAIL
        value: tijaniapatira@gmail.com# <-- REPLACE with your desired admin email
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Tijania32000 <-- REPLACE with a STRONG password (Render keeps this secure)

      # Add email credentials here if you use an SMTP backend (already in your current config)
      # - key: EMAIL_HOST
      #   value: "smtp.sendgrid.net"
      # - key: EMAIL_PORT
      #   value: "587"
      # - key: EMAIL_USE_TLS
      #   value: "True"
      # - key: EMAIL_HOST_USER
      #   value: "your_sendgrid_username"
      # - key: EMAIL_HOST_PASSWORD
      #   value: "your_sendgrid_api_key"
      # - key: DEFAULT_FROM_EMAIL
      #   value: "no-reply@yourdomain.com"


  - type: postgres
    name: myportfolio_db # Name of your PostgreSQL service
    plan: starter # Or 'free' if Render has a free tier for databases (check current offerings)
    databaseName: myportfolio_db # The database name inside Postgres
    user: myportfolio_user # The database user name inside Postgres
    # Optional: Initial database setup commands (e.g., creating extensions)
    # createCommands:
    #   - "CREATE EXTENSION IF NOT EXISTS hstore;" # Example