# Generated by Django 4.2.13 on 2025-05-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_premium', models.BooleanField(default=False, help_text='Set to true for custom quote plans')),
                ('features', models.TextField(help_text='Enter each feature on a new line')),
                ('button_text', models.CharField(default='Order Now', max_length=50)),
                ('button_url_name', models.CharField(default='contact:contact_page', help_text="URL name (e.g., 'contact:contact_page')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which plans are displayed')),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
    ]
