# Generated by Django 4.2.13 on 2025-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='note',
            field=models.CharField(blank=True, help_text="Optional note like: 'Best for enterprises, startups, and complex projects.'", max_length=255, null=True),
        ),
    ]
