# Generated by Django 4.2.13 on 2025-12-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
