# Generated by Django 4.2.13 on 2025-12-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='buyer_email',
        ),
    ]
