# Generated by Django 4.2.13 on 2025-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_email_order_buyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_name',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], default='paystack', max_length=20),
        ),
    ]
