# Generated by Django 4.2.13 on 2026-02-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_hostingplan_license_purchaserequest_sourcecodeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='whatsapp_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
