# Generated by Django 4.2.13 on 2026-02-07 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_purchaserequest_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/products/source/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed product writeup / documentation'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='products', to='marketplace.productimage'),
        ),
    ]
