# Generated by Django 4.2.13 on 2026-02-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_productimage_product_main_image_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
