# Generated by Django 4.2.13 on 2026-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_rename_price_product_price_with_both_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostingplan',
            old_name='price_per_month',
            new_name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_with_both',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_with_hosting',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_with_source_code',
        ),
        migrations.AddField(
            model_name='product',
            name='available_hosting_plans',
            field=models.ManyToManyField(blank=True, to='marketplace.hostingplan'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_full_ownership',
            field=models.DecimalField(decimal_places=2, default=1, help_text='One-time price for full source code ownership', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rental_setup_fee',
            field=models.DecimalField(decimal_places=2, default=1, help_text='One-time setup fee for managed/rental version', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='features',
            field=models.TextField(help_text='Separate features with commas'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic (Low Traffic)'), ('Pro', 'Pro (Medium Traffic)'), ('Enterprise', 'Enterprise (High Traffic/Company)')], max_length=100),
        ),
    ]
