# Generated by Django 4.2.13 on 2026-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_rename_price_per_month_hostingplan_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
