# Generated by Django 4.2.13 on 2026-02-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_hostingplan_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceCodeOption',
        ),
    ]
