# Generated by Django 4.2.13 on 2026-02-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_magiclinktoken_rental_rentalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_type',
            field=models.CharField(choices=[('full_ownership', 'Full Ownership (Source Code)'), ('rent_own', 'Rent & Own (Managed Hosting)')], max_length=20),
        ),
    ]
