# Generated by Django 4.2.13 on 2026-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_purchaserequest_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_full_ownership',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time price for full source code ownership', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_setup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time setup fee for managed/rental version', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_type',
            field=models.CharField(choices=[('full_ownership', 'Full Ownership (Source Code + Docs)'), ('rent_own', 'Rent & Host (Setup + Monthly)')], max_length=20),
        ),
    ]
