# Generated by Django 4.2.13 on 2026-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='domain_name',
            field=models.CharField(blank=True, max_length=253),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='domain_option',
            field=models.CharField(choices=[('none', 'No domain'), ('have_domain', 'I already have a domain'), ('need_domain', 'I want Sleekpedia to register a domain')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='domain_status',
            field=models.CharField(blank=True, default='unchecked', max_length=20),
        ),
    ]
